version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: { interval: weekly }
    labels: [dependances]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    labels: [dependances]
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
    labels: [dependances]
